### ISSUE TITLE
Loss Calculation 

### ISSUE THREAD

**Issue by shreyask3107** [cyhsu14/OmniNeRF#5]
Hi @cyhsu14 @sangminkim-99

Shouldn't we add the following line before 630 in run_nerf.py?
```
            rays_rgb_test = torch.reshape(rays_rgb_test, (11, 512, 1024, 3))
```
Majorly because the dimensions of rays_rgb_test and rgbs would not match in the either case

**Comment by sangminkim-99** [comment]
Hi @shreyk25 
I think you're right. They have different dimension.
In this code it calculates the mse between the last pixel value and the whole image.

Note that there is same error at line 499.

**Comment by shreyask3107** [comment]
Yes, Thanks for confirming! @sangminkim-99
